spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/edoc
    username: root
    password: ok

mybatis:
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8080

logging:
  level:
    root: info
    com.zb.mapper: debug
  config: classpath:lombok-spring.xml